[package]
name = "hue"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[workspace]
members = ["xtask"]

[dependencies]
atomic_float = "1.1"
nice-plug = { git = "https://codeberg.org/RustAudio/nice-plug.git", features = ["assert_process_allocs"] }
vizia_plug = { git = "https://github.com/vizia/vizia-plug.git" }
parking_lot = "0.12.1"
rand = "0.8.5"
rand_distr = "0.4.3"
realfft = "3.3.0"
triple_buffer = "9.0.0"

[patch."https://codeberg.org/BillyDM/nice-plug"]
nice-plug = { git = "https://codeberg.org/RustAudio/nice-plug.git" }
