name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  package:
    strategy:
      matrix:
        include:
          - { name: ubuntu-22.04,    os: ubuntu-22.04,   cross-target: '' }
          - { name: macos-universal, os: macos-14,       cross-target: '' }
          - { name: windows,         os: windows-latest, cross-target: '' }
    name: Package ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libgl-dev libjack-dev libxcb1-dev libxcb-icccm4-dev libxcursor-dev libxkbcommon-dev libxcb-shape0-dev libxcb-xfixes0-dev libx11-dev libxcb-dri2-0 libxcb-dri2-0-dev libx11-xcb-dev zip

      - uses: actions/cache@v4
        if: startsWith(matrix.os, 'windows')
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: release-${{ matrix.name }}-${{ matrix.cross-target }}
      - uses: actions/cache@v4
        if: startsWith(matrix.os, 'windows') != true
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: release-${{ matrix.name }}-${{ matrix.cross-target }}

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.cross-target }}

      - name: Install macOS universal build targets
        if: matrix.name == 'macos-universal'
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Package all targets from bundler.toml
        run: |
          package_args=()
          for package in $(cargo xtask known-packages); do
            package_args+=("-p" "$package")
          done

          runner_name=${{ matrix.name }}
          if [[ $runner_name = 'macos-universal' ]]; then
            export MACOSX_DEPLOYMENT_TARGET=10.13
            cargo xtask bundle-universal "${package_args[@]}" --release
          else
            cross_target=${{ matrix.cross-target }}
            if [[ -n $cross_target ]]; then
              package_args+=("--target" "$cross_target")
            fi

            cargo xtask bundle "${package_args[@]}" --release
          fi

      - name: Prepare release archive
        run: |
          ARCHIVE_NAME="hue-${GITHUB_REF_NAME}-${{ matrix.name }}"
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> "$GITHUB_ENV"
          mkdir -p "$ARCHIVE_NAME/$ARCHIVE_NAME"
          mv target/bundled/* "$ARCHIVE_NAME/$ARCHIVE_NAME"
          cp ".github/workflows/readme-${{ runner.os }}.txt" "$ARCHIVE_NAME/$ARCHIVE_NAME/README.txt"

      - name: Create zip archive
        if: runner.os != 'Windows'
        run: zip -r "$ARCHIVE_NAME.zip" "$ARCHIVE_NAME"

      - name: Create zip archive
        if: runner.os == 'Windows'
        shell: pwsh
        run: Compress-Archive -Path "$env:ARCHIVE_NAME" -DestinationPath "$env:ARCHIVE_NAME.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}.zip

  release:
    name: Publish GitHub Release
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: artifacts/*
